### ISSUE TITLE
Cajas de proyectos del HOME

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#1]
URL: https://www.propiapp.com/home
Home

![Image](https://github.com/user-attachments/assets/e1b185e4-3cbc-40ea-8a2a-c5d71b7c4472)
Ajustar mas los espacios entre items
Letra más pequeña para que no desborde.

¿Las cajas si tienen el mismo tamaño?

![Image](https://github.com/user-attachments/assets/91721dc8-de04-46a7-8054-6e7a9f722b98)
Tenemos una caja que esta desbordando abajo

![Image](https://github.com/user-attachments/assets/ea8c2f9b-90c3-4485-b3e7-2b69a2845e9a)

Tratemos de que quepan por lo menos 4~5 cajas en este espacio, así debamos apretar más aquí

**Comment by johnbeto20** [comment]
Acá @popeosorio solo nos caben 4 por el grid que usamos de boostrap, ya si ponemos 5 se vería apeñuscado.

**Comment by popeosorio** [comment]
@johnbeto20  sigue desbordando en pantallas mas pequeñas, por ejemplo en mi portatil sin pantalla conectada desborda precio y desborda nombre constructora

![Image](https://github.com/user-attachments/assets/39f9665d-8dea-48c9-b3b7-71b54b3cbade)

Tenemos dos opciones, poner mas chiquitas esas fuentes o que cuando la pantalla llegue a cierto tamaño se genere un carrusel de proyectos horizontal que vaya "moviendose".

Incluso esa parte final me parece interesante para meter no solo 4 proyectos, sino que salgan un par de proyectos adicionales.

@johnbeto20  lo muevo a pendiente nuevamente

![Image](https://github.com/user-attachments/assets/aba10f98-265a-4dff-94c1-045bf9967498)

**Comment by johnbeto20** [comment]
lo del  carrusel de proyectos horizontal lo pondría en el home... pero por el momento podríamos ir así? y ya en otra actualización lo ponemos así?

**Comment by popeosorio** [comment]
Voy a crear una historia con el deseo del carrusel.
