### ISSUE TITLE
poner un mas H y W para que galeria no genere doble scroll

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#10]
URL: https://www.propiapp.com/proyectos/detalle-proyecto-comprador/1

Cuando entro a la galeria y la imagen es muy grande, esta me genera doble scroll, coloquemos tamaño maximo de la pantalla para que no desborde.

![Image](https://github.com/user-attachments/assets/4f14a54c-a6ae-485d-b2ad-31e7136979f4)

PASA LO MISMO EN VISTA DE PLANOS.

**Comment by johnbeto20** [comment]
@popeosorio realizado.
