### ISSUE TITLE
Galeria permite ZOOM negativo hasta desaparecer

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#11]
En la galeria
URL: https://www.propiapp.com/proyectos/detalle-proyecto-comprador/1

![Image](https://github.com/user-attachments/assets/6af60cc7-87db-4003-bd1f-e1b1a5b6a821)
Permite hacer zoom "-" negativo, y desaparece la imagen.

No permitir zoom negativo si la imagen esta en el tamaño estandar.

PASA LO MISMO EN VISTA DE PLANOS.

**Comment by johnbeto20** [comment]
@popeosorio Ajustado
