### ISSUE TITLE
Ajustar ¿Que hay cerca?

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#12]
URL https://www.propiapp.com/proyectos/detalle-proyecto-comprador/1

En la pestaña que hay cerca los iconos estan desbordados.

![Image](https://github.com/user-attachments/assets/67cfff7c-6c84-477a-89b2-c0dc12ec2b4f)

me gustaria mas algo como en las zonas comunes, o otra propuesta de vista para esto donde  quede todo mas apretadito para optimizar espacio.

**Comment by johnbeto20** [comment]
Lo ajusté, aunque tenia otra propuesta con imagenes, pero con los iconos lo pude adaptar, si algo me la pasas en progress y revisamos propuestas.

**Comment by popeosorio** [comment]
Johnsito @johnbeto20  ¿que se te ocurre? antes de empezar a diseñar, aun no me convence.

![Image](https://github.com/user-attachments/assets/e871e9d3-b638-49ce-a6f6-138786d7a5e4)


Yo pensaria en agrupar por la categoria principal, como al estilo de las zonas comunes. ¿Como lo ves?

**Comment by johnbeto20** [comment]
tenia pensado algo con imagenes, pero no sé si pueda generar confusiones por que las personas esperarían la de la imagen. ya con la info propongo algo así:
![Image](https://github.com/user-attachments/assets/5ac270f1-e983-468c-ae9d-091b74d9e8a0)

**Comment by popeosorio** [comment]
Lo pongo en done y le pido a Luisa que le de una mirada
