### ISSUE TITLE
Apretar mas el resumen de proyecto

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#14]
URL: https://www.propiapp.com/proyectos/detalle-proyecto-comprador/1

Apretar mas el resume del proyecto para que no nos de tanto espacio arriba y abajo

![Image](https://github.com/user-attachments/assets/bf5502cf-a79d-4e59-a11f-c5da6b0a55a2)

**Comment by johnbeto20** [comment]
@popeosorio ajustado

**Comment by popeosorio** [comment]
Sigo viendo mucho espacio abajo.

Podemos disminuir la fuente de los titulos a ver si aptos por piso cabe en una linea

![Image](https://github.com/user-attachments/assets/44936277-1788-45c5-a706-89c114871b85)

**Comment by johnbeto20** [comment]
realizado los ajustes
