### ISSUE TITLE
Ajustar las zonas comunes

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#15]
¿Le podemos dar un aire a zonas comunes? 
URL https://www.propiapp.com/proyectos/detalle-proyecto-comprador/1

Se podria subir las zonas comunes cuando se terminen las otras?

o probamos apretando y eliminando ese monton de espacio que está quedando.

![Image](https://github.com/user-attachments/assets/78940de2-a78c-4433-b739-7da20c6e8ee1)

**Comment by johnbeto20** [comment]
Eliminé los espacios, si sería chevere pero dependemos de la información que se imprima.
