### ISSUE TITLE
Tipologia de viviendas

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#16]
URL https://www.propiapp.com/proyectos/detalle-proyecto-comprador/1

Podemos apretar esta tabla?
Podemos hacer que las amenidades se listen una al lado de la otra separadas por un pipe | o por un punto ° o una coma ,.

![Image](https://github.com/user-attachments/assets/c48523ce-7110-413c-b63d-198828eee3b2)

**Comment by johnbeto20** [comment]
@popeosorio ajustado

**Comment by popeosorio** [comment]
Podemos subir en amenidades y no usar el salto de linea sino que esten separadas con un pipe | por ejemplo 
![Image](https://github.com/user-attachments/assets/571b1769-7096-4506-8393-3e877aee1b28)


Adicional, podemos poner un poquito mas pequeña la letra en la negrita y la normal a ver si se ve más compacta.

@johnbeto20

**Comment by johnbeto20** [comment]
puse mas pequeña la fuente y le puse "," en línea se ve raro con las líneas.
![Image](https://github.com/user-attachments/assets/08d12807-e22f-4080-99a7-78af5a3ad004)
