### ISSUE TITLE
Cambiemos el item en negrita

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#17]
Que el titulo sea en negrita y el texto en fuente normal.
Dejemos el titulo pequeño en negrita
El texto del item que tenga una fuente mas razonable.
¿Podemos estandarizar eso?

![Image](https://github.com/user-attachments/assets/c159e5e3-f4d8-424a-b623-9437abe336ac)

**Comment by johnbeto20** [comment]
@popeosorio cómo lo ves así?

**Comment by popeosorio** [comment]
Dejemos así, aún no me convence la tendencia de todo gigante. Voy a seguir montando a ver si lo logro digerir.
