### ISSUE TITLE
Boton "todos los proyectos" se tapa cuando desborda una caja

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#2]
URL: https://www.propiapp.com/home
HOME

![Image](https://github.com/user-attachments/assets/504511fc-28f1-4cb8-9c06-52151d4474b5)
En caso tal de que en el responsive desborde, el boton se deberia ajustar al ultimo cajonsito.

**Comment by johnbeto20** [comment]
@popeosorio este ya quedó ajustado :D
