### ISSUE TITLE
Cuando me logeo, desaparecer COMENZAR GRATIS

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#20]
Lo cambiamos con un iconito circular de tu foto.
![Image](https://github.com/user-attachments/assets/12e2caf2-ac5f-4f74-957c-83733862dbc0)

![Image](https://github.com/user-attachments/assets/7e3129f4-270e-48f3-8e3b-424f56a34664)

**Comment by EsCastro89** [comment]
No estamos capturando fotos de la persona de momento, es necesario que la pidamos en el registro para poder mostrarla aca? Para ver si toca cambiar el flujo inicial y agregarla, por ahora solo lo quite al estar logeado

**Comment by popeosorio** [comment]
Luego hacemos el de la foto, de momento vamos así
