### ISSUE TITLE
Apretemos la tabla, se veía mucho mas limpia en la propuesta inicial de figma

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#21]
¿será la fuente?

URL https://www.propiapp.com/proyectos/listar-resumen-unidades-inversionista-proyecto?idCiudad=1&idDepartamento=1&nombreCiudad=Medell%C3%ADn&nombreDepartamento=Antioquia

![Image](https://github.com/user-attachments/assets/8654cf82-90a5-4836-95e9-1284554a4ebf)

**Comment by johnbeto20** [comment]
Ajustado, revisa por fa si así esta bien.
