### ISSUE TITLE
Caja de proyectos en "ver todos los proyectos"

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#43]
![Image](https://github.com/user-attachments/assets/116394b3-3bcd-4fe0-996c-81179e7ab605)
Esta desbordando tambien en algunos momentos. ¿Esos estilos no se pueden unificar para que cuando se toque en un lado se aplique a las 3 partes?

**Comment by johnbeto20** [comment]
Con el tema de las columnas de las card ya mitigamos esta parte
