### ISSUE TITLE
Almacenar el % de comisión que esta pagando actualmente.

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#44]
Esto se debe almacenar, es un porcentaje con decimales (Ej 1.5%, 3%)

Cada unidad puede tener un porcentaje diferente.

**Comment by johnbeto20** [comment]
este no lo entiendo, de pronto es para @EsCastro89 ??

**Comment by popeosorio** [comment]
Completado 
![Image](https://github.com/user-attachments/assets/ee1ebc3f-ce14-42ed-b1f3-b35d3e41443b)
