### ISSUE TITLE
Carrusel de proyectos en el Home (deseo)

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#45]
Que el carrusel de proyectos del home se le puedan meter varios proyectos en el home y vaya pasando solo y tenga flechas a los lados

![Image](https://github.com/user-attachments/assets/79f43a32-1182-4963-8554-8e11b751f13d)

**Comment by johnbeto20** [comment]
@popeosorio realizado, se verá en los proximos cambios adjuntos
