### ISSUE TITLE
Acomodar cajitas de proyectos

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#50]
Entendiendo que es culpa de los logos y que ya les hicimos un "FIX" maximo de tamaño que pueden tomar, cuando un logo es ancho y no cuadrado y/o alto, las cajitas toman tamaños mas pequeños.
¿Como hacemos un "FIX" para que las cajitas queden del mismo tamaño cuando llegue un logo que no es tan alto?

Esto aplica en dos partes. 1 En el HOME 

![Image](https://github.com/user-attachments/assets/609a6786-a943-4fd4-92e1-b9a4837bc63b)

En la pagina de busqueda normal

![Image](https://github.com/user-attachments/assets/75c9eaa1-4436-44e6-856f-30648058786e)

**Comment by johnbeto20** [comment]
@popeosorio ajustado :D
