### ISSUE TITLE
Caja de proyectos en la vista del listar proyectos

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#6]
URL: https://www.propiapp.com/proyectos/listar-resumen-unidades-proyecto?idCiudad=1&idDepartamento=1&nombreCiudad=Medell%C3%ADn&nombreDepartamento=Antioquia

La caja de proyectos  de esta vista:

![Image](https://github.com/user-attachments/assets/0c6ed6ad-e119-4d2b-b0ab-002c4c7e59f8)

No tiene los mismos estilos de la vista del home:

![Image](https://github.com/user-attachments/assets/dfd50d83-a01c-4f6b-a4d9-928cf83a49d6)

**Comment by johnbeto20** [comment]
@popeosorio listo, realizado.

**Comment by popeosorio** [comment]
Aquí pasa lo mismo que en el home, pero creo que aquí deberiamos de lograr que cuando la pantalla llegue a cierto tamaño, el grid cambie de 4 columnas a 3, a 2 y a 1 segun tamaño.

![Image](https://github.com/user-attachments/assets/5f9721d3-f3da-4ee8-9e6a-e37e276b3d2f)


Devuelvo a pendiente @johnbeto20

**Comment by johnbeto20** [comment]
Logrado

**Comment by popeosorio** [comment]
![Image](https://github.com/user-attachments/assets/b67c9f25-fa88-4b83-a7cf-350d718681d0)
Sigue pasando.

Utiliza el + y - del zoom del navegador para que valides de esa forma.

**Comment by popeosorio** [comment]
Genial!
