### ISSUE TITLE
Galeria del detalle proyecto no da clic para ampliar en las imagenes

### ISSUE THREAD

**Issue by popeosorio** [EsCastro89/ic-test#8]
URL: https://www.propiapp.com/proyectos/detalle-proyecto-comprador/1
La galeria deberia de poder dar clic no solo en el boton, el boton es un "plus" por si hay un dormido.

![Image](https://github.com/user-attachments/assets/962dc3e6-1990-49e4-9deb-71bf9652e84e)

PASA LO MISMO EN VISTA DE PLANOS.

**Comment by johnbeto20** [comment]
Puse el evento en las tres últimas imagenes. y organicé el responsive de la sección del galería y planos.
